-- ======================================================
-- SCRIPT DE CREACIÓN DE TABLA Y ALMACENAMIENTO PARA SUPABASE
-- Copia y pega este contenido en el SQL Editor de Supabase (https://app.supabase.com)
-- ======================================================

-- 1. Crear tabla principal de reportes
CREATE TABLE IF NOT EXISTS reportes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio VARCHAR(30) UNIQUE NOT NULL,
    tipo VARCHAR(30) NOT NULL,            -- 'queja', 'sugerencia'
    categoria VARCHAR(150) NOT NULL,
    urgencia VARCHAR(20) NOT NULL,        -- 'baja', 'media', 'alta'
    asunto VARCHAR(200) NOT NULL,
    descripcion TEXT NOT NULL,
    adjunto TEXT,                          -- Enlace público del archivo adjunto en Supabase Storage
    estado VARCHAR(30) DEFAULT 'Pendiente', -- 'Pendiente', 'En Revisión', 'En Proceso', 'Resuelto', 'Archivado'
    respuesta_admin TEXT,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Asegurar columna 'adjunto' si la tabla ya existía previamente
ALTER TABLE reportes ADD COLUMN IF NOT EXISTS adjunto TEXT;

-- 2. Índices para optimizar búsquedas por Folio y Estado
CREATE INDEX IF NOT EXISTS idx_reportes_folio ON reportes(folio);
CREATE INDEX IF NOT EXISTS idx_reportes_estado ON reportes(estado);

-- 3. Habilitar Seguridad a Nivel de Fila (RLS)
ALTER TABLE reportes ENABLE ROW LEVEL SECURITY;

-- Política 1: Permitir que cualquier usuario (anónimo) envíe reportes
CREATE POLICY "Permitir insercion anonima" ON reportes
    FOR INSERT WITH CHECK (true);

-- Política 2: Permitir consulta pública por Folio
CREATE POLICY "Permitir lectura publica" ON reportes
    FOR SELECT USING (true);

-- Política 3: Permitir actualización
CREATE POLICY "Permitir edicion" ON reportes
    FOR ALL USING (true);

-- ======================================================
-- PASO ADICIONAL EN SUPABASE STORAGE (GESTOR DE ARCHIVOS):
-- 1. Ve al menú "Storage" -> "New bucket"
-- 2. Nombra el bucket: evidencias-quejas
-- 3. Marca la casilla "Public bucket" (para permitir visualización pública de evidencias)
-- 4. ¡Listo! Los archivos se subirán de forma 100% anónima.
-- ======================================================
