

-- ======================================================
-- SCRIPT DE ESTRUCTURA Y SEGURIDAD BLINDADA PARA SUPABASE
-- Copia y pega este contenido en el SQL Editor de Supabase (https://app.supabase.com)
-- ======================================================

-- 1. Crear tabla principal de reportes
CREATE TABLE IF NOT EXISTS reportes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio VARCHAR(30) UNIQUE NOT NULL,
    tipo VARCHAR(30) NOT NULL,            -- 'queja', 'sugerencia'
    categoria VARCHAR(150) NOT NULL,
    urgencia VARCHAR(20) NOT NULL,        -- 'baja', 'media', 'alta'
    asunto VARCHAR(200) NOT NULL,
    descripcion TEXT NOT NULL,
    adjunto TEXT,                          -- Enlace público del archivo adjunto en Supabase Storage
    estado VARCHAR(30) DEFAULT 'Pendiente', -- 'Pendiente', 'En Revisión', 'En Proceso', 'Resuelto', 'Archivado'
    respuesta_admin TEXT,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Asegurar columna 'adjunto' si la tabla ya existía previamente
ALTER TABLE reportes ADD COLUMN IF NOT EXISTS adjunto TEXT;

-- 2. Índices para optimizar búsquedas por Folio y Estado
CREATE INDEX IF NOT EXISTS idx_reportes_folio ON reportes(folio);
CREATE INDEX IF NOT EXISTS idx_reportes_estado ON reportes(estado);

-- 3. Habilitar Seguridad a Nivel de Fila (RLS) en la tabla reportes
ALTER TABLE reportes ENABLE ROW LEVEL SECURITY;

-- Limpiar políticas previas para evitar conflictos
DROP POLICY IF EXISTS "Permitir insercion anonima" ON reportes;
DROP POLICY IF EXISTS "Permitir lectura publica" ON reportes;
DROP POLICY IF EXISTS "Permitir edicion" ON reportes;
DROP POLICY IF EXISTS "Permitir lectura solo a administradores" ON reportes;
DROP POLICY IF EXISTS "Permitir actualizacion solo a administradores" ON reportes;
DROP POLICY IF EXISTS "Permitir eliminacion solo a administradores" ON reportes;

-- Política 1 (Pública): Permitir que cualquier usuario (anónimo) envíe reportes
CREATE POLICY "Permitir insercion anonima" ON reportes
    FOR INSERT TO anon, authenticated
    WITH CHECK (true);

-- Política 2 (Privada): Permitir lectura completa de reportes SOLO a administradores autenticados
CREATE POLICY "Permitir lectura solo a administradores" ON reportes
    FOR SELECT TO authenticated
    USING (true);

-- Política 3 (Privada): Permitir edición/actualización de reportes SOLO a administradores autenticados
CREATE POLICY "Permitir actualizacion solo a administradores" ON reportes
    FOR UPDATE TO authenticated
    USING (true)
    WITH CHECK (true);

-- Política 4 (Privada): Permitir borrado de reportes SOLO a administradores autenticados
CREATE POLICY "Permitir eliminacion solo a administradores" ON reportes
    FOR DELETE TO authenticated
    USING (true);

-- ======================================================
-- 4. FUNCIÓN RPC SEGURA PARA CONSULTA PÚBLICA POR FOLIO ÚNICO
-- Permite consultar UN solo reporte por su código de folio sin exponer toda la tabla
-- ======================================================
CREATE OR REPLACE FUNCTION consultar_reporte_por_folio(p_folio TEXT)
RETURNS SETOF reportes
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT *
    FROM reportes
    WHERE UPPER(folio) = UPPER(TRIM(p_folio))
    LIMIT 1;
$$;

-- Permitir que usuarios anónimos y autenticados puedan invocar la función de consulta por folio
GRANT EXECUTE ON FUNCTION consultar_reporte_por_folio(TEXT) TO anon, authenticated;

-- ======================================================
-- 5. CONFIGURACIÓN DE SUPABASE STORAGE (BUCKET Y POLÍTICAS RLS)
-- ======================================================

-- Crear el bucket 'evidencias_quejas' como público si no existe
INSERT INTO storage.buckets (id, name, public)
VALUES ('evidencias_quejas', 'evidencias_quejas', true)
ON CONFLICT (id) DO NOTHING;

-- Política RLS 1: Permitir subir archivos (INSERT) públicamente al bucket 'evidencias_quejas'
DROP POLICY IF EXISTS "Permitir subida publica en evidencias_quejas" ON storage.objects;
CREATE POLICY "Permitir subida publica en evidencias_quejas" ON storage.objects
    FOR INSERT TO anon, authenticated
    WITH CHECK (bucket_id = 'evidencias_quejas');

-- Política RLS 2: Permitir ver/descargar archivos (SELECT) públicamente del bucket 'evidencias_quejas'
DROP POLICY IF EXISTS "Permitir lectura publica en evidencias_quejas" ON storage.objects;
CREATE POLICY "Permitir lectura publica en evidencias_quejas" ON storage.objects
    FOR SELECT TO anon, authenticated
    USING (bucket_id = 'evidencias_quejas');

-- Política RLS 3: Permitir borrar archivos (DELETE) SOLO a administradores autenticados
DROP POLICY IF EXISTS "Permitir eliminacion publica en evidencias_quejas" ON storage.objects;
DROP POLICY IF EXISTS "Permitir eliminacion solo a administradores en evidencias_quejas" ON storage.objects;
CREATE POLICY "Permitir eliminacion solo a administradores en evidencias_quejas" ON storage.objects
    FOR DELETE TO authenticated
    USING (bucket_id = 'evidencias_quejas');


