import React, { useState } from 'react';
import { X, Github, Database, Mail, CheckCircle2, Copy, HardDrive } from 'lucide-react';

interface GitHubInstructionsModalProps {
  onClose: () => void;
}

export const GitHubInstructionsModal: React.FC<GitHubInstructionsModalProps> = ({ onClose }) => {
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  const copyToClipboard = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const sqlScript = `CREATE TABLE IF NOT EXISTS reportes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio VARCHAR(30) UNIQUE NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    categoria VARCHAR(150) NOT NULL,
    urgencia VARCHAR(20) NOT NULL,
    asunto VARCHAR(200) NOT NULL,
    descripcion TEXT NOT NULL,
    adjunto TEXT,
    estado VARCHAR(30) DEFAULT 'Pendiente',
    respuesta_admin TEXT,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE reportes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir todo publica" ON reportes FOR ALL USING (true);`;

  const envExample = `VITE_SUPABASE_URL=https://tu-proyecto.supabase.co
VITE_SUPABASE_ANON_KEY=tu-anon-key-de-supabase
VITE_WEB3FORMS_ACCESS_KEY=tu-clave-web3forms
VITE_ADMIN_PASSWORD=admin123`;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm animate-fade-in">
      <div className="bg-white w-full max-w-3xl max-h-[90vh] rounded-3xl overflow-hidden flex flex-col shadow-2xl border border-slate-200">
        
        {/* Modal Header */}
        <div className="flex items-center justify-between px-6 py-5 border-b border-slate-200 bg-slate-50">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 rounded-2xl bg-indigo-50 text-indigo-600 border border-indigo-200">
              <Github className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-900">Guía de Conexión a Supabase (Base de Datos + Archivos)</h2>
              <p className="text-xs text-slate-500 font-medium">Paso a paso para conectar tu base de datos y la carga anónima de evidencias</p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-slate-700 hover:bg-slate-200 transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Content */}
        <div className="p-6 overflow-y-auto space-y-6 text-slate-700 text-xs">
          
          {/* PASO 1: Supabase DB */}
          <div className="bg-slate-50 p-5 rounded-2xl border border-slate-200 space-y-3">
            <div className="flex items-center space-x-2 text-emerald-700 font-bold text-sm">
              <Database className="w-4 h-4" />
              <span>1. Crear Proyecto y Tabla en Supabase (Gratis)</span>
            </div>
            <ol className="list-decimal list-inside space-y-1 text-slate-700 font-medium leading-relaxed pl-1">
              <li>Ingresa a <a href="https://app.supabase.com" target="_blank" rel="noreferrer" className="text-emerald-700 underline font-bold">app.supabase.com</a> y crea un nuevo proyecto gratuito.</li>
              <li>Entra a la sección <b>SQL Editor</b> e ingresa el siguiente código:</li>
            </ol>

            <div className="relative">
              <pre className="bg-slate-900 p-3.5 rounded-xl border border-slate-800 font-mono text-[11px] text-emerald-300 max-h-36 overflow-y-auto">
                {sqlScript}
              </pre>
              <button
                onClick={() => copyToClipboard(sqlScript, 1)}
                className="absolute right-2 top-2 p-1.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-300"
              >
                {copiedIndex === 1 ? <CheckCircle2 className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              </button>
            </div>
          </div>

          {/* PASO 2: Supabase Storage */}
          <div className="bg-slate-50 p-5 rounded-2xl border border-slate-200 space-y-3">
            <div className="flex items-center space-x-2 text-indigo-700 font-bold text-sm">
              <HardDrive className="w-4 h-4" />
              <span>2. Crear Bucket para Archivos Anónimos (Supabase Storage)</span>
            </div>
            <ol className="list-decimal list-inside space-y-1.5 text-slate-700 font-medium leading-relaxed pl-1">
              <li>En la consola de Supabase, ve al menú lateral <b>Storage</b>.</li>
              <li>Haz clic en <b>New Bucket</b>.</li>
              <li>Ingresa el nombre del bucket: <code className="bg-white border border-slate-300 px-1.5 py-0.5 rounded text-indigo-700 font-mono font-bold">evidencias-quejas</code></li>
              <li><b>IMPORTANTE:</b> Activa la opción <b>Public bucket</b> (para permitir la descarga/visualización de evidencias adjuntas).</li>
            </ol>
          </div>

          {/* PASO 3: Variables de Entorno */}
          <div className="bg-slate-50 p-5 rounded-2xl border border-slate-200 space-y-3">
            <div className="flex items-center space-x-2 text-cyan-700 font-bold text-sm">
              <Mail className="w-4 h-4" />
              <span>3. Configurar Claves en tu archivo .env o en GitHub Actions</span>
            </div>
            <p className="text-slate-700 font-medium">
              Obtén tu <b>Project URL</b> y <b>anon public API Key</b> en <i>Project Settings -&gt; API</i> y agrégalas a tu archivo <code className="bg-white border border-slate-300 px-1.5 py-0.5 rounded text-indigo-700 font-mono font-bold">.env</code>:
            </p>
            <div className="relative">
              <pre className="bg-slate-900 p-3.5 rounded-xl border border-slate-800 font-mono text-[11px] text-cyan-300 overflow-x-auto">
                {envExample}
              </pre>
              <button
                onClick={() => copyToClipboard(envExample, 2)}
                className="absolute right-2 top-2 p-1.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-300"
              >
                {copiedIndex === 2 ? <CheckCircle2 className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              </button>
            </div>
          </div>

        </div>

        {/* Modal Footer */}
        <div className="px-6 py-4 border-t border-slate-200 bg-slate-50 text-right">
          <button
            onClick={onClose}
            className="px-6 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs transition shadow-md shadow-indigo-600/20"
          >
            Entendido
          </button>
        </div>

      </div>
    </div>
  );
};
